# Dependencies
markdown:         kramdown
highlighter:      pygments

gems:
  - jekyll-redirect-from

# Setup
title:            'Smartling'
tagline:          'Developer Documentation'
description:      'Developer documentation for the Smartling platform.'
url:              http://hyde.getpoole.com
baseurl:          '/'

author:
  name:           'Smartling'
  url:            http://www.smartling.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
